# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0003_postlike_created_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postlike',
            table=None,
        ),
    ]
