# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0011_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cars',
            field=models.ManyToManyField(related_name='introduction_to_models_students', related_query_name='introduction_to_models_students', to='introduction_to_models.Car'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cars',
            field=models.ManyToManyField(related_name='introduction_to_models_teachers', related_query_name='introduction_to_models_teachers', to='introduction_to_models.Car'),
        ),
    ]
